// Central lookup for DOM elements used across modules.

export function collectDomElements() {
  const elements = {
    svg: document.getElementById('network'),
    stage: document.getElementById('stage'),
    sidebar: document.getElementById('sidebar'),
    tooltip: document.getElementById('tooltip'),
    mainLayout: document.getElementById('mainLayout'),
    rangeStart: document.getElementById('rangeStart'),
    rangeEnd: document.getElementById('rangeEnd'),
    rangeTrack: document.getElementById('rangeTrack'),
    progressLabel: document.getElementById('progressLabel'),
    sidebarHint: document.getElementById('sidebarHint'),
    sidebarTitle: document.getElementById('sidebarTitle'),
    sidebarBackBtn: document.getElementById('sidebarBackBtn'),
    sidebarHomeBtn: document.getElementById('sidebarHomeBtn'),
    browsePanel: document.getElementById('browsePanel'),
    browseStatus: document.getElementById('browseStatus'),
    browseList: document.getElementById('browseList'),
    charPanel: document.getElementById('charPanel'),
    charHeader: document.getElementById('charHeader'),
    charSummary: document.getElementById('charSummary'),
    charTabs: document.getElementById('charTabs'),
    tabFacts: document.getElementById('tabFacts'),
    tabRels: document.getElementById('tabRels'),
    viewFacts: document.getElementById('viewFacts'),
    viewRels: document.getElementById('viewRels'),
    charStatus: document.getElementById('charStatus'),
    eventList: document.getElementById('eventList'),
    relList: document.getElementById('relList'),
    charRelStatus: document.getElementById('charRelStatus'),
    interPanel: document.getElementById('interPanel'),
    interHeader: document.getElementById('interHeader'),
    interSummary: document.getElementById('interSummary'),
    interStatus: document.getElementById('interStatus'),
    interEventList: document.getElementById('interEventList'),
    textDock: document.getElementById('textDock'),
    textFrame: document.getElementById('textFrame'),
    textCloseBtn: document.getElementById('textCloseBtn'),
    textZoomInBtn: document.getElementById('textZoomInBtn'),
    textZoomOutBtn: document.getElementById('textZoomOutBtn'),
    handleStageSidebar: document.getElementById('handleStageSidebar'),
    handleDockStage: document.getElementById('handleDockStage'),
    toggleTextDockBtn: document.getElementById('toggleTextDockBtn'),
    charFactHistEl: document.getElementById('charFactHist'),
    charInterHistEl: document.getElementById('charInterHist'),
    interFactHistEl: document.getElementById('interFactHist'),
    interSentChartEl: document.getElementById('interSentChart'),
  };
  return elements;
}
